-- MySQL Script generated by MySQL Workbench
-- sáb 15 feb 2020 12:49:51 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema portalDeIdeas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema portalDeIdeas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `portalDeIdeas` DEFAULT CHARACTER SET latin1 ;
USE `portalDeIdeas` ;

-- -----------------------------------------------------
-- Table `portalDeIdeas`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portalDeIdeas`.`users` ;

CREATE TABLE IF NOT EXISTS `portalDeIdeas`.`users` (
  `user_id` CHAR(36) NOT NULL,
  `email` TEXT NOT NULL,
  `password` TEXT NOT NULL,
  `name` VARCHAR(25) NOT NULL,
  `surname` VARCHAR(45) NULL DEFAULT NULL,
  `avatar_url` TEXT NULL DEFAULT NULL,
  `role` CHAR(3) NOT NULL,
  `contact_email` TEXT NULL DEFAULT NULL,
  `contact_web` TEXT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `portalDeIdeas`.`projects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portalDeIdeas`.`projects` ;

CREATE TABLE IF NOT EXISTS `portalDeIdeas`.`projects` (
  `project_id` CHAR(36) NOT NULL,
  `user_id` CHAR(36) NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `details` TEXT NOT NULL,
  `category` VARCHAR(15) NOT NULL,
  `complexity` INT(1) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `closed_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`project_id`),
  INDEX `user_id` (`user_id` ASC),
  CONSTRAINT `projects_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `portalDeIdeas`.`users` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `portalDeIdeas`.`documents`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portalDeIdeas`.`documents` ;

CREATE TABLE IF NOT EXISTS `portalDeIdeas`.`documents` (
  `doc_id` CHAR(36) NOT NULL,
  `project_id` CHAR(36) NOT NULL,
  `user_id` CHAR(36) NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `file_url` TEXT NOT NULL,
  `rating` INT(1) NULL DEFAULT NULL,
  `uploaded_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`doc_id`),
  INDEX `project_id` (`project_id` ASC),
  INDEX `user_id` (`user_id` ASC),
  CONSTRAINT `documents_ibfk_1`
    FOREIGN KEY (`project_id`)
    REFERENCES `portalDeIdeas`.`projects` (`project_id`),
  CONSTRAINT `documents_ibfk_2`
    FOREIGN KEY (`user_id`)
    REFERENCES `portalDeIdeas`.`users` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `portalDeIdeas`.`users_projects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portalDeIdeas`.`users_projects` ;

CREATE TABLE IF NOT EXISTS `portalDeIdeas`.`users_projects` (
  `user_id` CHAR(36) NOT NULL,
  `project_id` CHAR(36) NOT NULL,
  PRIMARY KEY (`user_id`, `project_id`),
  INDEX `fk_users_has_projects_projects1_idx` (`project_id` ASC),
  INDEX `fk_users_has_projects_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_users_has_projects_projects1`
    FOREIGN KEY (`project_id`)
    REFERENCES `portalDeIdeas`.`projects` (`project_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_projects_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `portalDeIdeas`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

USE `portalDeIdeas` ;

-- -----------------------------------------------------
-- Placeholder table for view `portalDeIdeas`.`documentsAndUsers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portalDeIdeas`.`documentsAndUsers` (`doc_id` INT, `project_id` INT, `user_id` INT, `user_name` INT, `user_avatar_url` INT, `title` INT, `file_url` INT, `rating` INT, `uploaded_at` INT, `deleted_at` INT);

-- -----------------------------------------------------
-- Placeholder table for view `portalDeIdeas`.`projectsAndFollowers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portalDeIdeas`.`projectsAndFollowers` (`project_id` INT, `user_id` INT, `user_name` INT, `user_avatar_url` INT, `title` INT, `description` INT, `details` INT, `category` INT, `complexity` INT, `created_at` INT, `updated_at` INT, `closed_at` INT, `number_of_followers` INT);

-- -----------------------------------------------------
-- View `portalDeIdeas`.`documentsAndUsers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portalDeIdeas`.`documentsAndUsers`;
DROP VIEW IF EXISTS `portalDeIdeas`.`documentsAndUsers` ;
USE `portalDeIdeas`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `portalDeIdeas`.`documentsAndUsers` AS select `portalDeIdeas`.`documents`.`doc_id` AS `doc_id`,`portalDeIdeas`.`documents`.`project_id` AS `project_id`,`portalDeIdeas`.`documents`.`user_id` AS `user_id`,`portalDeIdeas`.`users`.`name` AS `user_name`,`portalDeIdeas`.`users`.`avatar_url` AS `user_avatar_url`,`portalDeIdeas`.`documents`.`title` AS `title`,`portalDeIdeas`.`documents`.`file_url` AS `file_url`,`portalDeIdeas`.`documents`.`rating` AS `rating`,`portalDeIdeas`.`documents`.`uploaded_at` AS `uploaded_at`,`portalDeIdeas`.`documents`.`deleted_at` AS `deleted_at` from (`portalDeIdeas`.`documents` join `portalDeIdeas`.`users` on((`portalDeIdeas`.`documents`.`user_id` = `portalDeIdeas`.`users`.`user_id`))) order by `portalDeIdeas`.`documents`.`uploaded_at` desc;

-- -----------------------------------------------------
-- View `portalDeIdeas`.`projectsAndFollowers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portalDeIdeas`.`projectsAndFollowers`;
DROP VIEW IF EXISTS `portalDeIdeas`.`projectsAndFollowers` ;
USE `portalDeIdeas`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `portalDeIdeas`.`projectsAndFollowers` AS select `portalDeIdeas`.`projects`.`project_id` AS `project_id`,`portalDeIdeas`.`projects`.`user_id` AS `user_id`,`portalDeIdeas`.`users`.`name` AS `user_name`,`portalDeIdeas`.`users`.`avatar_url` AS `user_avatar_url`,`portalDeIdeas`.`projects`.`title` AS `title`,`portalDeIdeas`.`projects`.`description` AS `description`,`portalDeIdeas`.`projects`.`details` AS `details`,`portalDeIdeas`.`projects`.`category` AS `category`,`portalDeIdeas`.`projects`.`complexity` AS `complexity`,`portalDeIdeas`.`projects`.`created_at` AS `created_at`,`portalDeIdeas`.`projects`.`updated_at` AS `updated_at`,`portalDeIdeas`.`projects`.`closed_at` AS `closed_at`,count(`portalDeIdeas`.`users_projects`.`project_id`) AS `number_of_followers` from ((`portalDeIdeas`.`projects` left join `portalDeIdeas`.`users_projects` on((`portalDeIdeas`.`projects`.`project_id` = `portalDeIdeas`.`users_projects`.`project_id`))) join `portalDeIdeas`.`users` on((`portalDeIdeas`.`projects`.`user_id` = `portalDeIdeas`.`users`.`user_id`))) group by `portalDeIdeas`.`projects`.`project_id` order by `portalDeIdeas`.`projects`.`created_at` desc;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
