-- MySQL Script generated by MySQL Workbench
-- vie 20 dic 2019 12:27:03 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema portalDeIdeas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema portalDeIdeas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `portalDeIdeas` DEFAULT CHARACTER SET latin1 ;
USE `portalDeIdeas` ;

-- -----------------------------------------------------
-- Table `portalDeIdeas`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portalDeIdeas`.`users` (
  `user_id` CHAR(36) NOT NULL,
  `email` TEXT NOT NULL,
  `password` TEXT NOT NULL,
  `name` VARCHAR(25) NOT NULL,
  `surname` VARCHAR(45) NULL DEFAULT NULL,
  `avatar_url` TEXT NULL DEFAULT NULL,
  `role` CHAR(3) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `portalDeIdeas`.`projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portalDeIdeas`.`projects` (
  `project_id` CHAR(36) NOT NULL,
  `user_id` CHAR(36) NOT NULL,
  `tltle` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `details` TEXT NOT NULL,
  `target` VARCHAR(20) NOT NULL,
  `sector` VARCHAR(15) NOT NULL,
  `theme` VARCHAR(15) NOT NULL,
  `complexity` INT(1) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`project_id`),
  INDEX `user_id` (`user_id` ASC),
  CONSTRAINT `projects_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `portalDeIdeas`.`users` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `portalDeIdeas`.`documents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portalDeIdeas`.`documents` (
  `doc_id` CHAR(36) NOT NULL,
  `project_id` CHAR(36) NOT NULL,
  `user_id` CHAR(36) NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `file_url` TEXT NOT NULL,
  `uploaded_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`doc_id`),
  INDEX `project_id` (`project_id` ASC),
  INDEX `user_id` (`user_id` ASC),
  CONSTRAINT `documents_ibfk_1`
    FOREIGN KEY (`project_id`)
    REFERENCES `portalDeIdeas`.`projects` (`project_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `documents_ibfk_2`
    FOREIGN KEY (`user_id`)
    REFERENCES `portalDeIdeas`.`users` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
